bash guard clauses

diff --git a/bin/dsky b/bin/dsky
--- a/bin/dsky
+++ b/bin/dsky
@@ -12,56 +12,57 @@ export REST=$(echo "$@" |cut -d' ' -f 3-)
 if [ -z $1 ]; then
     # help screen
     echo "dsky SUBJECT VERB"
-else
-    # Set NOUN
-    if [ $1 == '.' ]; then
-        NOUN=`pwd | rev | cut -d'/' -f1 |rev`
-    else
-        NOUN=$1
-    fi
-
-    PROJ_DIR="$PROJECTS/$NOUN"
-    hi $NOUN 
-    BRANCH=`git branch | grep "*" | cut -d' ' -f2`
-
-    if [ -d $PROJ_DIR ]; then
-
-      cd $PROJ_DIR
-
-      case "$2" in
-      stat )    # tc build 
-                # github prs
-                git diff --stat
-                echo "pull requests"
-                dsky $1 pr
-                ;;
-      # editors
-      e )       $EDITOR;;
-      edit )    $EDITOR;;
-      vi )      vi;;
-      idea )    idea $1;;
-      # git
-      github )  open "http://github.com/`cat .git/config | grep url | cut -d: -f2 | cut -d. -f1`";; # open or xdg-open
-      pr )      open "https://github.com/$GIT_ORG/$NOUN/compare/master...$BRANCH";;
-      prs )     hub pr list -s open -L 10 --format="%l%i %au: %t %uI %Nc%n    a:%as  r:%rs  %L%n";; # %sC for color
-      prc )     hub pr checkout $3;;
-      add )     git add $(REST);;
-      commit )  git commit $(REST);;
-      push )    git push origin;;
-      stash )   git stash $(REST);;
-      rebase )  git pull --rebase origin master;;
-      co )      git checkout $3;;
-      branch )  git branch $REST;;
-      run )     docker run $REST $1;;
-      status )  git status;;
-      isgo )    git status;;
-      '' )      git status;;
-      * )       make $2;;
-      esac
-
-    else 
-      # not a local ~/project 
-      echo "SUBJECT $NOUN not found."
-    fi
+    return 0
 fi
+
+# Set NOUN
+if [ $1 == '.' ]; then
+    NOUN=`pwd | rev | cut -d'/' -f1 |rev`
+else
+    NOUN=$1
+    NOUN_ONLY=`echo $1 | cut -d/ -f2`
+fi
+
+PROJ_DIR="$PROJECTS/$NOUN_ONLY"
+hi $NOUN 
+BRANCH=`git branch | grep "*" | cut -d' ' -f2`
+
+if ! [ -d $PROJ_DIR ]; then
+  # not a local ~/project 
+  echo "SUBJECT $NOUN not found."
+  return
+fi
+
+cd $PROJ_DIR
+
+case "$2" in
+stat )  # tc build 
+        # github prs
+        git diff --stat
+        echo "pull requests"
+        dsky $1 pr
+        ;;
+# editors
+e )       $EDITOR;;
+edit )    $EDITOR;;
+vi )      vi;;
+idea )    idea $1;;
+# git
+github )  open "http://github.com/`cat .git/config | grep url | cut -d: -f2 | cut -d. -f1`";; # open or xdg-open
+pr )      open "https://github.com/$GIT_ORG/$NOUN/compare/master...$BRANCH";;
+prs )     hub pr list -s open -L 10 --format="%l%i %au: %t %uI %Nc%n    a:%as  r:%rs  %L%n";; # %sC for color
+prc )     hub pr checkout $3;;
+add )     git add $(REST);;
+commit )  git commit $(REST);;
+push )    git push origin;;
+stash )   git stash $(REST);;
+rebase )  git pull --rebase origin master;;
+co )      git checkout $3;;
+branch )  git branch $REST;;
+run )     docker run $REST $1;;
+status )  git status;;
+isgo )    git status;;
+'' )      git status;;
+* )       make $2;;
+esac
 
diff --git a/bin/hi b/bin/hi
--- a/bin/hi
+++ b/bin/hi
@@ -5,36 +5,38 @@ PRESENT=${PWD##*/}
 GIT_USER=trevorgrayson
 GIT_ORG=retentionscience
 GIT_HOST=git@github.com
-PROJECT=$1
-REPO=$GIT_HOST:$GIT_ORG/$PROJECT.git
+LOCATION=$1
+PROJECT=`echo $1 | cut -d/ -f2`
+REPO=$GIT_HOST:$GIT_ORG/$LOCATION.git
+
+cd $PROJECTS
 
 if [ -z "$PROJECT" ]; then
   echo "please provide a project"
   cd $PROJECTS
-
-else
-  if [ -d $PROJECTS/$PROJECT ]; then
-    cd $PROJECTS/$PROJECT
-    command -v title && title $PROJECT
-    git fetch &
-    git status
-
-  else 
-    if [ -n "$HAPI_REPO" ]; then
-      echo "Getting $PROJECT from $REPO"
-      cd $PROJECTS
-
-      if [[ $PROJECT == *"/"* ]]; then    # detect slash and optionally include org
-          PROJECT=`echo $PROJECT | cut -d'/' -f2`
-          git clone $REPO
-          cd $PROJECT
-      else
-          git clone -q $REPO 2>/dev/null || echo "$REPO not found, checking $GIT_USER/$PROJECT" && \
-          git clone "$GIT_HOST:$GIT_USER/$PROJECT.git"
-          cd $PROJECT
-      fi
-      command -v title && title $1
-    fi
-  fi
+  return
 fi
 
+if [ -d $PROJECTS/$PROJECT ]; then # project is checked out in the $PROJECTS folder
+    cd $PROJECTS/$PROJECT
+    test -n `command -v title` && title $PROJECT # set terminal title, if possible
+    git fetch &
+    # git status
+    return
+fi
+
+if [ -n "$REPO" ]; then
+  echo "Getting $PROJECT from $REPO"
+  cd $PROJECTS
+
+  if [[ $PROJECT == *"/"* ]]; then    # detect slash and optionally include org
+      git clone $REPO
+      cd $PROJECT
+  else
+      git clone -q $REPO 2>/dev/null || echo "$REPO not found, checking $GIT_USER/$PROJECT" && \
+      git clone "$GIT_HOST:$GIT_USER/$PROJECT.git"
+      cd $PROJECT
+  fi
+
+  test -n `command -v title` && title $PROJECT
+fi
