dsky: owner/proj and killing title

diff --git a/bin/dsky b/bin/dsky
--- a/bin/dsky
+++ b/bin/dsky
@@ -9,7 +9,7 @@ function hi {
   PROJECTS=${PROJECTS:=$HOME/projects}
   PRESENT=${PWD##*/}
   # GIT_USER
-  GIT_ORG=retentionscience
+  # GIT_ORG=
   GIT_HOST=git@github.com
   LOCATION=$1
   PROJECT=`echo $1 | cut -d/ -f2`
@@ -24,25 +24,31 @@ function hi {
 
   if [ -d $PROJECTS/$PROJECT ]; then              # project is present in $PROJECTS dir
     cd $PROJECTS/$PROJECT
-    test -n `command -v title` && title $PROJECT  # set terminal title, if possible
+    # command -v 'title' && title $PROJECT  # set terminal title, if possible
     # git status
     return
   fi
 
+  echo $LOCATION
   if [ -n "$REPO" ]; then
-    echo "Getting $PROJECT from $GIT_HOST:$GIT_ORG/$PROJECT.git"
+    echo "Getting $PROJECT from $GIT_HOST" # :$GIT_ORG/$PROJECT.git"
 
     # if test -z $GIT_USER; then
     #     echo "please set $GIT_USER. consider adding the following to ~/.bashrc"
     #     echo "export GIT_USER=\"$USER\""
     # fi
 
-    git clone -q "$GIT_HOST:$GIT_ORG/$PROJECT.git" || echo "$REPO not found, checking $GIT_USER/$PROJECT" && \
-    git clone -q "$GIT_HOST:$GIT_USER/$PROJECT.git" || echo "Not found."
+    if [[ "$LOCATION" == *\/* ]]; then 
+      echo "git clone -q '$GIT_HOST:$LOCATION.git'"
+      git clone -q "$GIT_HOST:$LOCATION.git" || echo "$REPO not found, checking $GIT_USER/$PROJECT"
+    else
+      git clone -q "$GIT_HOST:$GIT_ORG/$PROJECT.git" || echo "$REPO not found, checking $GIT_USER/$PROJECT" && \
+      git clone -q "$GIT_HOST:$GIT_USER/$PROJECT.git" || echo "Not found."
+    fi
 
     test -d $PROJECT && cd $PROJECT || echo "Repo not found" && return 1
 
-    test -n `command -v title` && title $PROJECT
+    # test -n `command -v title` && title $PROJECT
   fi
   return 0
 }
@@ -53,7 +59,7 @@ export REST=$(echo "$@" |cut -d' ' -f 3-)
 if [ -z $1 ]; then
     # help screen
     echo "dsky SUBJECT VERB"
-    return 0
+    exit 0
 fi
 
 # Set NOUN
@@ -77,7 +83,8 @@ else
   test -f dsky.notes && cat dsky.notes
   git fetch &
 
-  (find . -name '*.py' > cscope.files & find . -name '*.rb' >> cscope.files) && cscope -b 
+  # need to abstract this
+  # test -n `command -v cscope` && (find . -name '*.py' > cscope.files & find . -name '*.rb' >> cscope.files) && cscope -b 
 fi
 
 cd $PROJ_DIR
